image: node:lts

stages:
  - lint
  - test

install:
  stage: .pre
  script: yarn
  artifacts:
    name: 'artifacts'
    untracked: true
    expire_in: 60 mins
    paths:
      - .npm/
      - node_modules/

eslint:
  stage: lint
  script: yarn run eslint
  dependencies:
    - install

typescript:
  stage: lint
  script: yarn run tsc
  dependencies:
    - install

unit:
  stage: test
  script: yarn run test
  dependencies:
    - install
