image: node:lts

stages:
  - lint
  - test
  - deploy

install:
  stage: .pre
  script: yarn
  artifacts:
    name: "artifacts"
    untracked: true
    expire_in: 60 mins
    paths:
      - .npm/
      - node_modules/

eslint:
  stage: lint
  script: yarn run eslint
  dependencies:
    - install

typescript:
  stage: lint
  script: yarn run tsc
  dependencies:
    - install

unit:
  stage: test
  script: yarn run test
  dependencies:
    - install

integration:
  stage: test
  image: alekzonder/puppeteer:latest
  script: yarn run build && yarn run test:integration
  dependencies:
    - install
  artifacts:
    name: "artifacts"
    untracked: true
    expire_in: 60 mins
    paths:
      - build/

heroku:
  stage: deploy
  image: ruby:2.6.5
  script:
    - apt-get update -qy
    - apt-get install -yqq ruby ruby-dev nodejs --silent
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
  only:
    - develop

aws:
  stage: deploy
  image: python:latest
  before_script:
    - pip install awscli
  script:
    - aws s3 rm s3://$BUCKET_NAME/ --recursive 
    - aws s3 cp build s3://$BUCKET_NAME --recursive 
  dependencies:
    - integration
  only:
    - master

